# Generated by Django 5.0.7 on 2024-08-08 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialGeek', '0005_gweek_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gweek',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='gweek_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
