# Generated by Django 5.0.7 on 2024-08-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialGeek', '0007_gweek_facebook_link_gweek_home_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gweek',
            old_name='home_link',
            new_name='home_page_link',
        ),
    ]
