# Generated by Django 5.0.7 on 2024-08-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialGeek', '0008_rename_home_link_gweek_home_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gweek',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gweek',
            name='home_page_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gweek',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gweek',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
