# Generated by Django 5.0.7 on 2024-08-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialGeek', '0009_alter_gweek_facebook_link_alter_gweek_home_page_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gweek',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='gweek',
            name='home_page_link',
        ),
        migrations.RemoveField(
            model_name='gweek',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='gweek',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='gweek',
            name='profile_bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_page_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
